#!/bin/bash
# Brainstorm Skill Script / 头脑风暴技能脚本
# Copyright (c) 2026 OASYS CORE INTERNATIONAL LIMITED / 潤芯國際(香港)有限公司

set -e

echo "🧠 DragonStack Brainstorm Skill / 头脑风暴技能"
echo "==============================================="
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check if we're in a project directory / 检查是否在项目目录
if [ ! -f "./DRAGONSTACK.md" ] && [ ! -d "./.dragonstack" ]; then
    echo -e "${YELLOW}⚠️ No DragonStack project detected / 未检测到龙栈项目${NC}"
    echo "Run this from your project root / 请从项目根目录运行"
    exit 1
fi

# Create docs directory if not exists / 创建 docs 目录（如果不存在）
mkdir -p docs

# Get current date / 获取当前日期
DATE=$(date +%Y-%m-%d)
OUTPUT_FILE="docs/brainstorm-${DATE}.md"

echo -e "${BLUE}📋 Brainstorm Framework / 头脑风暴框架${NC}"
echo ""
echo "This skill will guide you through: / 本技能将引导你完成："
echo "  1. 5W1H Analysis / 5W1H 分析"
echo "  2. Problem Reframing / 问题重构"
echo "  3. Solution Alternatives / 解决方案替代方案"
echo "  4. Effort Estimation / 工作量估算"
echo ""

# Prompt user for input / 提示用户输入
echo -e "${YELLOW}💡 Describe your product idea / 描述你的产品想法:${NC}"
echo "   (What problem are you solving? Who is it for?)"
echo "   （你在解决什么问题？为谁而做？）"
echo ""
echo "   Type your idea and press Ctrl+D when done:"
echo "   输入你的想法，完成后按 Ctrl+D："
echo ""

# Read user input / 读取用户输入
USER_IDEA=$(cat)

# Generate output / 生成输出
echo ""
echo -e "${BLUE}📝 Generating design document... / 生成设计文档...${NC}"

cat > "$OUTPUT_FILE" << EOF
# Brainstorm Output: Product Design Document / 头脑风暴输出：产品设计文档

**Date / 日期**: ${DATE}  
**Project / 项目**: $(basename "$(pwd)")  
**Skill / 技能**: /brainstorm

---

## 1. Original Idea / 原始想法

${USER_IDEA}

---

## 2. 5W1H Analysis / 5W1H 分析

### What / 什么
- What are you building? / 你在构建什么？
- [To be filled during session]

### Why / 为什么
- Why does this matter? / 为什么这很重要？
- What pain points does it solve? / 它解决了什么痛点？

### Who / 谁
- Who is your target user? / 你的目标用户是谁？
- What are their characteristics? / 他们有什么特征？

### When / 何时
- When will users use this? / 用户何时使用？
- What triggers usage? / 什么触发使用？

### Where / 何地
- Where will this run? / 这将在哪里运行？
- What platforms? / 什么平台？

### How / 如何
- How will it work? / 它将如何工作？
- What are the key interactions? / 关键交互是什么？

---

## 3. Problem Reframing / 问题重构

After analysis, consider: / 分析后，考虑：

- Is your initial framing correct? / 你最初的框架正确吗？
- What assumptions are you making? / 你在做什么假设？
- What if the real problem is different? / 如果真正的问题不同呢？

---

## 4. Solution Alternatives / 解决方案替代方案

### Option 1: MVP (1 week) / 方案 1：最小可行产品（1周）
- Core functionality only / 仅核心功能
- Manual processes acceptable / 可接受手动流程
- Validate demand first / 先验证需求

### Option 2: Standard (1 month) / 方案 2：标准版本（1月）
- Full feature set / 完整功能集
- Automated workflows / 自动化工作流
- Production-ready / 生产就绪

### Option 3: Vision (3 months) / 方案 3：愿景版本（3月）
- Complete platform / 完整平台
- Advanced features / 高级功能
- Scale-ready / 可扩展

---

## 5. Recommendation / 建议

**Recommended approach / 推荐方案**: [MVP / Standard / Vision]

**Rationale / 理由**:
- [Explain why / 解释原因]

---

## 6. Next Steps / 下一步

- [ ] Review this document with stakeholders / 与利益相关者审查本文档
- [ ] Run /ceo-review for strategic alignment / 运行 /ceo-review 进行战略对齐
- [ ] Run /arch-design for technical planning / 运行 /arch-design 进行技术规划
- [ ] Set up project structure / 设置项目结构
- [ ] Begin implementation / 开始实现

---

*Generated by DragonStack /brainstorm skill / 由龙栈 /brainstorm 技能生成*
EOF

echo ""
echo -e "${GREEN}✅ Brainstorm document created! / 头脑风暴文档已创建！${NC}"
echo ""
echo "📄 Output file / 输出文件: ${OUTPUT_FILE}"
echo ""
echo -e "${YELLOW}📋 Next steps / 下一步:${NC}"
echo "   1. Review and fill in the 5W1H analysis / 审查并填写 5W1H 分析"
echo "   2. Discuss with your team / 与团队讨论"
echo "   3. Run /ceo-review for strategic input / 运行 /ceo-review 获取战略输入"
echo ""
echo "🧠 Happy brainstorming! / 头脑风暴愉快！"
