# MAWA Core Components / MAWA 核心组件
# DragonStack 3.0 / 龙栈 3.0
# Copyright (c) 2026 OASYS CORE INTERNATIONAL LIMITED

# MAWA Architecture:
# - Registration: Skill 能力边界声明
# - Playbook: 执行策略和进化机制  
# - TaskRun: 审计日志和追踪
# - Dispatcher: 智能路由引擎

DRAGONSTACK_VERSION="3.0-2026.03.29"
DRAGONSTACK_MAWA_VERSION="1.0-2026.03.29"

# Colors - using tput for portability
if command -v tput &> /dev/null && [ -n "$TERM" ] && [ "$TERM" != "dumb" ]; then
    MAWA_RED=$(tput setaf 1)
    MAWA_GREEN=$(tput setaf 2)
    MAWA_YELLOW=$(tput setaf 3)
    MAWA_BLUE=$(tput setaf 4)
    MAWA_PURPLE=$(tput setaf 5)
    MAWA_CYAN=$(tput setaf 6)
    MAWA_NC=$(tput sgr0)
else
    MAWA_RED=""
    MAWA_GREEN=""
    MAWA_YELLOW=""
    MAWA_BLUE=""
    MAWA_PURPLE=""
    MAWA_CYAN=""
    MAWA_NC=""
fi

# MAWA Paths
MAWA_DIR="${SCRIPT_DIR}/mawa"
MAWA_REGISTRY_DIR="${MAWA_DIR}/registry"
MAWA_PLAYBOOK_DIR="${MAWA_DIR}/playbook"
MAWA_TASKRUN_DIR="${MAWA_DIR}/taskrun"
MAWA_DISPATCHER_DIR="${MAWA_DIR}/dispatcher"

# Ensure MAWA directories exist
ensure_mawa_dirs() {
    mkdir -p "$MAWA_REGISTRY_DIR"
    mkdir -p "$MAWA_PLAYBOOK_DIR"
    mkdir -p "$MAWA_TASKRUN_DIR"
    mkdir -p "$MAWA_DISPATCHER_DIR"
}

# ============================================
# REGISTRATION - Skill 能力边界声明
# ============================================

# Register a skill with its capabilities
register_skill() {
    local skill_name="$1"
    local skill_version="$2"
    local capabilities="$3"
    local constraints="$4"
    
    local reg_file="${MAWA_REGISTRY_DIR}/${skill_name}.reg"
    
    cat > "$reg_file" << EOF
# Skill Registration / 技能注册
# Generated by MAWA Registration System

skill:
  name: ${skill_name}
  version: ${skill_version}
  registered_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
  
capabilities:
${capabilities}

constraints:
${constraints}

boundaries:
  # Hard boundaries - what this skill CANNOT do
  cannot:
    - execute_destructive_commands_without_confirmation
    - access_sensitive_credentials_directly
    - bypass_user_approval_for_external_actions
    
  # Soft boundaries - requires additional confirmation
  requires_confirmation:
    - git_push_to_production
    - database_modifications
    - api_key_generation
EOF

    echo -e "${MAWA_GREEN}✅ Registered skill: ${skill_name} v${skill_version}${MAWA_NC}"
}

# Get skill capabilities
get_skill_capabilities() {
    local skill_name="$1"
    local reg_file="${MAWA_REGISTRY_DIR}/${skill_name}.reg"
    
    if [ -f "$reg_file" ]; then
        grep -A 20 "capabilities:" "$reg_file" | grep "  -" | sed 's/  - //'
    else
        echo ""
    fi
}

# Check if skill can perform action
can_skill_perform() {
    local skill_name="$1"
    local action="$2"
    
    local capabilities=$(get_skill_capabilities "$skill_name")
    
    if echo "$capabilities" | grep -q "$action"; then
        return 0
    else
        return 1
    fi
}

# ============================================
# PLAYBOOK - 执行策略和进化机制
# ============================================

# Playbook states: PILOT -> BETA -> STABLE -> SOTA
PLAYBOOK_STATE_PILOT="pilot"
PLAYBOOK_STATE_BETA="beta"
PLAYBOOK_STATE_STABLE="stable"
PLAYBOOK_STATE_SOTA="sota"  # State of the Art

# Initialize playbook for a skill
init_playbook() {
    local skill_name="$1"
    local initial_strategy="$2"
    
    local playbook_file="${MAWA_PLAYBOOK_DIR}/${skill_name}.playbook"
    
    cat > "$playbook_file" << EOF
# Playbook / 执行策略
# Skill: ${skill_name}
# Evolution: PILOT → BETA → STABLE → SOTA

metadata:
  skill: ${skill_name}
  created_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
  current_state: ${PLAYBOOK_STATE_PILOT}
  version: 1.0.0
  
strategy:
${initial_strategy}

execution:
  max_retries: 3
  timeout_seconds: 300
  require_confirmation: false
  
evolution:
  pilot:
    description: "Initial implementation, manual review required"
    auto_promote_after: 10
    success_rate_threshold: 0.7
    
  beta:
    description: "Tested implementation, reduced oversight"
    auto_promote_after: 50
    success_rate_threshold: 0.85
    
  stable:
    description: "Proven implementation, minimal oversight"
    auto_promote_after: 100
    success_rate_threshold: 0.95
    
  sota:
    description: "State of the Art, self-improving"
    continuous_learning: true
    
metrics:
  total_executions: 0
  successful_executions: 0
  failed_executions: 0
  average_duration_ms: 0
  last_execution_at: null
EOF

    echo -e "${MAWA_BLUE}📖 Initialized playbook for: ${skill_name} (${PLAYBOOK_STATE_PILOT})${MAWA_NC}"
}

# Get current playbook state
get_playbook_state() {
    local skill_name="$1"
    local playbook_file="${MAWA_PLAYBOOK_DIR}/${skill_name}.playbook"
    
    if [ -f "$playbook_file" ]; then
        grep "current_state:" "$playbook_file" | head -1 | awk '{print $2}'
    else
        echo "$PLAYBOOK_STATE_PILOT"
    fi
}

# Update playbook metrics
update_playbook_metrics() {
    local skill_name="$1"
    local success="$2"  # true/false
    local duration_ms="$3"
    
    local playbook_file="${MAWA_PLAYBOOK_DIR}/${skill_name}.playbook"
    
    if [ ! -f "$playbook_file" ]; then
        return 1
    fi
    
    # Update execution counts
    local total=$(grep "total_executions:" "$playbook_file" | awk '{print $2}')
    total=$((total + 1))
    
    local successful=$(grep "successful_executions:" "$playbook_file" | awk '{print $2}')
    local failed=$(grep "failed_executions:" "$playbook_file" | awk '{print $2}')
    
    if [ "$success" = "true" ]; then
        successful=$((successful + 1))
    else
        failed=$((failed + 1))
    fi
    
    # Update file using awk for cross-platform compatibility
    awk -v tot="$total" -v suc="$successful" -v fail="$failed" -v ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ") '
        { 
            gsub(/total_executions: .*/, "total_executions: " tot)
            gsub(/successful_executions: .*/, "successful_executions: " suc)
            gsub(/failed_executions: .*/, "failed_executions: " fail)
            gsub(/last_execution_at: .*/, "last_execution_at: " ts)
            print
        }
    ' "$playbook_file" > "${playbook_file}.tmp"
    mv "${playbook_file}.tmp" "$playbook_file"
    
    # Check for evolution
    check_playbook_evolution "$skill_name"
}

# Check if playbook should evolve to next state
check_playbook_evolution() {
    local skill_name="$1"
    local playbook_file="${MAWA_PLAYBOOK_DIR}/${skill_name}.playbook"
    
    local current_state=$(get_playbook_state "$skill_name")
    local total=$(grep "total_executions:" "$playbook_file" | awk '{print $2}')
    local successful=$(grep "successful_executions:" "$playbook_file" | awk '{print $2}')
    
    if [ "$total" -eq 0 ]; then
        return 0
    fi
    
    local success_rate=$(echo "scale=2; $successful / $total" | bc)
    
    case "$current_state" in
        "$PLAYBOOK_STATE_PILOT")
            if [ "$total" -ge 10 ] && [ "$(echo "$success_rate >= 0.7" | bc -l)" -eq 1 ]; then
                awk -v state="$PLAYBOOK_STATE_BETA" '{ gsub(/current_state: .*/, "current_state: " state); print }' "$playbook_file" > "${playbook_file}.tmp"
                mv "${playbook_file}.tmp" "$playbook_file"
                echo "${MAWA_GREEN}🎉 Playbook evolved: ${skill_name} → ${PLAYBOOK_STATE_BETA}${MAWA_NC}"
            fi
            ;;
        "$PLAYBOOK_STATE_BETA")
            if [ "$total" -ge 50 ] && [ "$(echo "$success_rate >= 0.85" | bc -l)" -eq 1 ]; then
                awk -v state="$PLAYBOOK_STATE_STABLE" '{ gsub(/current_state: .*/, "current_state: " state); print }' "$playbook_file" > "${playbook_file}.tmp"
                mv "${playbook_file}.tmp" "$playbook_file"
                echo "${MAWA_GREEN}🎉 Playbook evolved: ${skill_name} → ${PLAYBOOK_STATE_STABLE}${MAWA_NC}"
            fi
            ;;
        "$PLAYBOOK_STATE_STABLE")
            if [ "$total" -ge 100 ] && [ "$(echo "$success_rate >= 0.95" | bc -l)" -eq 1 ]; then
                awk -v state="$PLAYBOOK_STATE_SOTA" '{ gsub(/current_state: .*/, "current_state: " state); print }' "$playbook_file" > "${playbook_file}.tmp"
                mv "${playbook_file}.tmp" "$playbook_file"
                echo "${MAWA_PURPLE}🏆 Playbook evolved: ${skill_name} → ${PLAYBOOK_STATE_SOTA} (State of the Art)${MAWA_NC}"
            fi
            ;;
    esac
}

# ============================================
# TASKRUN - 审计日志和追踪
# ============================================

# Start a new task run
start_taskrun() {
    local task_name="$1"
    local skill_name="$2"
    local user_input="$3"
    
    local taskrun_id="tr_$(date +%s)_$(openssl rand -hex 4 2>/dev/null || echo $$)"
    local taskrun_file="${MAWA_TASKRUN_DIR}/${taskrun_id}.yaml"
    
    cat > "$taskrun_file" << EOF
# TaskRun / 任务执行记录
# ID: ${taskrun_id}

metadata:
  taskrun_id: ${taskrun_id}
  task_name: ${task_name}
  skill: ${skill_name}
  started_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
  status: running
  
input:
  user_command: "${user_input}"
  
execution_chain: []

output:
  result: null
  artifacts: []
  
metrics:
  duration_ms: 0
  tokens_used: 0
  api_calls: 0
EOF

    echo "$taskrun_id"
}

# Log execution step
log_taskrun_step() {
    local taskrun_id="$1"
    local step_name="$2"
    local step_type="$3"  # skill, agent, tool, decision
    local details="$4"
    
    local taskrun_file="${MAWA_TASKRUN_DIR}/${taskrun_id}.yaml"
    
    if [ ! -f "$taskrun_file" ]; then
        return 1
    fi
    
    # Create temp file with new step appended
    local temp_file="${taskrun_file}.tmp"
    awk -v step="$step_name" -v stype="$step_type" -v ts="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" -v det="$details" '
        /execution_chain: \[\]/ {
            print
            print "  - step: " step
            print "    type: " stype
            print "    timestamp: " ts
            print "    details: " det
            next
        }
        { print }
    ' "$taskrun_file" > "$temp_file"
    mv "$temp_file" "$taskrun_file"
}

# Complete task run
complete_taskrun() {
    local taskrun_id="$1"
    local status="$2"  # success, failed, cancelled
    local result="$3"
    local duration_ms="$4"
    
    local taskrun_file="${MAWA_TASKRUN_DIR}/${taskrun_id}.yaml"
    
    if [ ! -f "$taskrun_file" ]; then
        return 1
    fi
    
    # Use awk for cross-platform compatibility
    awk -v st="$status" -v res="$result" -v dur="$duration_ms" '
        { 
            gsub(/status: running/, "status: " st)
            gsub(/result: null/, "result: " res)
            gsub(/duration_ms: 0/, "duration_ms: " dur)
            print
        }
    ' "$taskrun_file" > "${taskrun_file}.tmp"
    mv "${taskrun_file}.tmp" "$taskrun_file"
    
    # Update playbook metrics
    local skill_name=$(grep "skill:" "$taskrun_file" | head -1 | awk '{print $2}')
    local success="false"
    if [ "$status" = "success" ]; then
        success="true"
    fi
    update_playbook_metrics "$skill_name" "$success" "$duration_ms"
}

# Get recent task runs
get_recent_taskruns() {
    local limit="${1:-10}"
    
    ls -t "${MAWA_TASKRUN_DIR}"/*.yaml 2>/dev/null | head -"$limit" | while read -r f; do
        local id=$(basename "$f" .yaml)
        local task=$(grep "task_name:" "$f" | awk '{print $2}')
        local skill=$(grep "skill:" "$f" | head -1 | awk '{print $2}')
        local status=$(grep "status:" "$f" | head -1 | awk '{print $2}')
        echo "${id}: ${task} (${skill}) - ${status}"
    done
}

# ============================================
# DISPATCHER - 智能路由引擎
# ============================================

# ATC: Agent Task Card (W/H/A/T)
# W - What/Why: 任务目标和原因
# H - How: 执行步骤
# A - Automation: 自动化程度
# T - Test/Verify: 验证方式

# Parse natural language to ATC
parse_natural_language() {
    local input="$1"
    
    # Simple keyword-based parsing (can be enhanced with NLP)
    local what=""
    local how=""
    local automation="partial"
    local test=""
    
    # Detect intent
    if echo "$input" | grep -qi "brainstorm\|idea\|构思"; then
        what="brainstorm_product_ideation"
        how="generate_ideas_and_concepts"
        suggested_skill="brainstorm"
    elif echo "$input" | grep -qi "design\|架构\|设计"; then
        what="architecture_design"
        how="create_technical_specification"
        suggested_skill="design"
    elif echo "$input" | grep -qi "code\|write\|implement\|实现"; then
        what="code_generation"
        how="generate_implementation_code"
        suggested_skill="code"
    elif echo "$input" | grep -qi "review\|检查\|审查"; then
        what="code_review"
        how="analyze_code_quality"
        suggested_skill="code-review"
    elif echo "$input" | grep -qi "test\|测试"; then
        what="test_planning"
        how="create_test_strategy"
        suggested_skill="test"
    elif echo "$input" | grep -qi "ship\|deploy\|发布\|部署"; then
        what="release_deployment"
        how="git_commit_and_push"
        suggested_skill="ship"
    elif echo "$input" | grep -qi "debug\|fix\|bug\|修复"; then
        what="debugging"
        how="diagnose_and_fix_issues"
        suggested_skill="debug"
    elif echo "$input" | grep -qi "doc\|document\|文档"; then
        what="documentation"
        how="generate_project_docs"
        suggested_skill="doc"
    elif echo "$input" | grep -qi "refactor\|重构\|优化"; then
        what="code_refactoring"
        how="improve_code_structure"
        suggested_skill="refactor"
    else
        what="general_task"
        how="analyze_and_execute"
        suggested_skill="brainstorm"
    fi
    
    echo "ATC:"
    echo "  W (What/Why): $what"
    echo "  H (How): $how"
    echo "  A (Automation): $automation"
    echo "  T (Test): validation_required"
    echo "  Suggested Skill: $suggested_skill"
}

# Dispatch task to appropriate skill
dispatch_task() {
    local user_input="$1"
    local taskrun_id="$2"
    
    echo "${MAWA_CYAN}🎯 Dispatcher: Analyzing task...${MAWA_NC}"
    
    # Simple keyword-based dispatch
    local suggested_skill="brainstorm"
    
    if echo "$user_input" | grep -qiE "(design|架构|设计|schema)"; then
        suggested_skill="design"
    elif echo "$user_input" | grep -qiE "(code|write|implement|实现|生成.*代码|写.*代码)"; then
        suggested_skill="code"
    elif echo "$user_input" | grep -qiE "(review|检查|审查)"; then
        suggested_skill="code-review"
    elif echo "$user_input" | grep -qiE "(test|测试)"; then
        suggested_skill="test"
    elif echo "$user_input" | grep -qiE "(ship|deploy|发布|部署)"; then
        suggested_skill="ship"
    elif echo "$user_input" | grep -qiE "(debug|fix|bug|修复)"; then
        suggested_skill="debug"
    elif echo "$user_input" | grep -qiE "(doc|document|文档)"; then
        suggested_skill="doc"
    elif echo "$user_input" | grep -qiE "(refactor|重构|优化)"; then
        suggested_skill="refactor"
    elif echo "$user_input" | grep -qiE "(brainstorm|idea|构思|想法)"; then
        suggested_skill="brainstorm"
    fi
    
    echo "${MAWA_BLUE}📋 ATC Parsed:${MAWA_NC}"
    echo "  W (What/Why): user_request"
    echo "  H (How): execute_${suggested_skill}_skill"
    echo "  A (Automation): partial"
    echo "  T (Test): validation_required"
    echo "  Suggested Skill: ${suggested_skill}"
    
    # Check if skill is registered
    local reg_file="${MAWA_REGISTRY_DIR}/${suggested_skill}.reg"
    if [ ! -f "$reg_file" ]; then
        echo "${MAWA_YELLOW}⚠️  Skill not registered: ${suggested_skill}${MAWA_NC}"
        echo "${MAWA_YELLOW}   Auto-registering...${MAWA_NC}"
        auto_register_skill "$suggested_skill"
    fi
    
    # Get playbook state
    local playbook_state=$(get_playbook_state "$suggested_skill")
    echo "${MAWA_BLUE}📖 Playbook State: ${playbook_state}${MAWA_NC}"
    
    # Log dispatch decision
    if [ -n "$taskrun_id" ]; then
        log_taskrun_step "$taskrun_id" "dispatch" "decision" "routed_to_${suggested_skill}"
    fi
    
    # Return suggested skill
    echo "$suggested_skill"
}

# Auto-register a skill with default capabilities
auto_register_skill() {
    local skill_name="$1"
    
    case "$skill_name" in
        "brainstorm")
            register_skill "$skill_name" "3.0.0" \
                "  - product_ideation
  - feature_planning
  - concept_generation
  - user_story_creation" \
                "  - requires_user_input: true
  - max_output_length: 5000_words"
            ;;
        "design")
            register_skill "$skill_name" "3.0.0" \
                "  - architecture_design
  - api_specification
  - database_schema
  - system_diagrams" \
                "  - requires_approval: true
  - max_complexity: enterprise"
            ;;
        "code")
            register_skill "$skill_name" "3.0.0" \
                "  - code_generation
  - multi_language_support
  - framework_integration
  - acp_agent_integration" \
                "  - languages: go,python,javascript,typescript,rust
  - requires_review: true"
            ;;
        "code-review")
            register_skill "$skill_name" "3.0.0" \
                "  - static_analysis
  - security_scanning
  - best_practices_check
  - performance_review" \
                "  - severity_threshold: medium
  - auto_fix: false"
            ;;
        "test")
            register_skill "$skill_name" "3.0.0" \
                "  - test_planning
  - unit_test_generation
  - integration_testing
  - coverage_analysis" \
                "  - min_coverage: 80%
  - test_frameworks: multiple"
            ;;
        "ship")
            register_skill "$skill_name" "3.0.0" \
                "  - git_operations
  - release_management
  - changelog_generation
  - deployment_automation" \
                "  - protected_branches: main,master
  - require_ci_pass: true"
            ;;
        "debug")
            register_skill "$skill_name" "3.0.0" \
                "  - error_analysis
  - log_parsing
  - system_diagnostics
  - fix_suggestion" \
                "  - destructive_commands: forbidden
  - backup_required: true"
            ;;
        "doc")
            register_skill "$skill_name" "3.0.0" \
                "  - readme_generation
  - api_documentation
  - code_comments
  - changelog_creation" \
                "  - formats: markdown,html,pdf
  - auto_sync: true"
            ;;
        "refactor")
            register_skill "$skill_name" "3.0.0" \
                "  - code_restructuring
  - pattern_application
  - debt_reduction
  - performance_optimization" \
                "  - behavior_preservation: required
  - test_coverage_maintained: true"
            ;;
    esac
    
    # Initialize playbook
    init_playbook "$skill_name" "  default_strategy: standard_execution"
}

# ============================================
# MAWA CLI Commands
# ============================================

mawa_status() {
    printf "${MAWA_CYAN}🐉 DragonStack MAWA Status${MAWA_NC}\n"
    echo "=========================="
    echo ""
    printf "${MAWA_BLUE}Version:${MAWA_NC} ${DRAGONSTACK_VERSION} (MAWA ${DRAGONSTACK_MAWA_VERSION})\n"
    echo ""
    
    printf "${MAWA_GREEN}Registered Skills:${MAWA_NC}\n"
    local count=0
    for reg in "${MAWA_REGISTRY_DIR}"/*.reg; do
        if [ -f "$reg" ]; then
            local name=$(basename "$reg" .reg)
            local version=$(grep "version:" "$reg" | head -1 | awk '{print $2}')
            local state=$(get_playbook_state "$name")
            echo "  ✓ ${name} v${version} [${state}]"
            count=$((count + 1))
        fi
    done
    echo ""
    echo "Total: $count skills registered"
    echo ""
    
    printf "${MAWA_YELLOW}Recent TaskRuns:${MAWA_NC}\n"
    get_recent_taskruns 5 | sed 's/^/  /'
}

mawa_inspect_skill() {
    local skill_name="$1"
    local reg_file="${MAWA_REGISTRY_DIR}/${skill_name}.reg"
    local playbook_file="${MAWA_PLAYBOOK_DIR}/${skill_name}.playbook"
    
    echo -e "${MAWA_CYAN}🔍 Inspecting Skill: ${skill_name}${MAWA_NC}"
    echo ""
    
    if [ -f "$reg_file" ]; then
        echo -e "${MAWA_GREEN}Registration:${MAWA_NC}"
        cat "$reg_file" | sed 's/^/  /'
    else
        echo -e "${MAWA_RED}  Not registered${MAWA_NC}"
    fi
    
    echo ""
    
    if [ -f "$playbook_file" ]; then
        echo -e "${MAWA_GREEN}Playbook:${MAWA_NC}"
        cat "$playbook_file" | sed 's/^/  /'
    else
        echo -e "${MAWA_RED}  No playbook${MAWA_NC}"
    fi
}

# Export functions for use in dragonstack main script
export -f register_skill
export -f get_skill_capabilities
export -f can_skill_perform
export -f init_playbook
export -f get_playbook_state
export -f update_playbook_metrics
export -f start_taskrun
export -f log_taskrun_step
export -f complete_taskrun
export -f get_recent_taskruns
export -f parse_natural_language
export -f dispatch_task
export -f mawa_status
export -f mawa_inspect_skill
export -f ensure_mawa_dirs
