#!/bin/bash
# Ship Skill Script / 发布技能脚本
# Copyright (c) 2026 OASYS CORE INTERNATIONAL LIMITED / 潤芯國際(香港)有限公司

set -e

echo "🚀 DragonStack Ship Skill / 发布技能"
echo "======================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check if we're in a git repository
if [ ! -d ".git" ]; then
    echo -e "${YELLOW}⚠️ Not a git repository / 不是 git 仓库${NC}"
    echo "Please run 'git init' first / 请先运行 'git init'"
    exit 1
fi

# Check if we're in a project directory
if [ ! -f "./DRAGONSTACK.md" ] && [ ! -d "./.dragonstack" ]; then
    echo -e "${YELLOW}⚠️ No DragonStack project detected / 未检测到龙栈项目${NC}"
    echo "Run this from your project root / 请从项目根目录运行"
    exit 1
fi

echo -e "${BLUE}🚀 Starting ship process... / 开始发布流程...${NC}"
echo ""

# Step 1: Check git status
echo "Step 1: Checking git status / 步骤 1: 检查 git 状态..."
if git diff-index --quiet HEAD --; then
    echo -e "${YELLOW}⚠️ No changes to commit / 没有要提交的更改${NC}"
    echo "Make some changes before shipping / 在发布前做一些更改"
    exit 1
fi

echo -e "${GREEN}✅ Changes detected / 检测到更改${NC}"
echo ""

# Step 2: Show changes
echo "Step 2: Changes to be shipped / 步骤 2: 要发布的更改..."
git status --short
echo ""

# Step 3: Ask for confirmation
echo -e "${YELLOW}📋 Review the changes above / 审查上面的更改${NC}"
read -p "Continue with ship? (yes/no) / 继续发布? (yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
    echo -e "${YELLOW}⚠️ Ship cancelled / 发布已取消${NC}"
    exit 0
fi

# Step 4: Run tests if available
echo ""
echo "Step 3: Running tests / 步骤 3: 运行测试..."
if [ -f "package.json" ] && grep -q "test" package.json; then
    if npm test 2>/dev/null; then
        echo -e "${GREEN}✅ Tests passed / 测试通过${NC}"
    else
        echo -e "${RED}❌ Tests failed / 测试失败${NC}"
        read -p "Continue anyway? (yes/no) / 仍然继续? (yes/no): " CONTINUE
        if [ "$CONTINUE" != "yes" ]; then
            exit 1
        fi
    fi
else
    echo -e "${YELLOW}⚠️ No tests found / 未找到测试${NC}"
fi
echo ""

# Step 5: Commit changes
echo "Step 4: Committing changes / 步骤 4: 提交更改..."
read -p "Enter commit message / 输入提交信息: " COMMIT_MSG

if [ -z "$COMMIT_MSG" ]; then
    COMMIT_MSG="Update from DragonStack /ship"
fi

git add -A
git commit -m "$COMMIT_MSG"
echo -e "${GREEN}✅ Changes committed / 更改已提交${NC}"
echo ""

# Step 6: Push to remote
echo "Step 5: Pushing to remote / 步骤 5: 推送到远程..."
if git remote -v > /dev/null 2>&1; then
    CURRENT_BRANCH=$(git branch --show-current)
    git push origin "$CURRENT_BRANCH"
    echo -e "${GREEN}✅ Pushed to origin/$CURRENT_BRANCH / 已推送到 origin/$CURRENT_BRANCH${NC}"
else
    echo -e "${YELLOW}⚠️ No remote configured / 未配置远程仓库${NC}"
    echo "Add a remote with: git remote add origin <url>"
fi
echo ""

# Generate report
DATE=$(date +%Y-%m-%d)
OUTPUT_FILE="docs/ship-${DATE}.md"
mkdir -p docs

cat > "$OUTPUT_FILE" << EOF
# Ship Report / 发布报告

**Date / 日期**: ${DATE}  
**Project / 项目**: $(basename "$(pwd)")  
**Skill / 技能**: /ship

---

## 1. Ship Summary / 发布摘要

| Step / 步骤 | Status / 状态 |
|------------|--------------|
| Git Status Check / Git 状态检查 | ✅ Passed |
| Tests / 测试 | ⏳ See below |
| Commit / 提交 | ✅ Done |
| Push / 推送 | ✅ Done |

---

## 2. Commit Details / 提交详情

- **Message / 信息**: $COMMIT_MSG
- **Branch / 分支**: $(git branch --show-current)
- **Remote / 远程**: $(git remote get-url origin 2>/dev/null || echo "Not configured")

---

## 3. Next Steps / 下一步

- [ ] Create Pull Request on GitHub / 在 GitHub 上创建 Pull Request
- [ ] Wait for CI/CD to pass / 等待 CI/CD 通过
- [ ] Request code review / 请求代码审查
- [ ] Merge to main branch / 合并到主分支
- [ ] Run /deploy to deploy to production / 运行 /deploy 部署到生产环境

---

*Generated by DragonStack /ship skill / 由龙栈 /ship 技能生成*
EOF

echo -e "${GREEN}✅ Ship complete! / 发布完成！${NC}"
echo ""
echo "📄 Report saved to / 报告保存至: ${OUTPUT_FILE}"
echo ""
echo -e "${YELLOW}📋 Next steps / 下一步:${NC}"
echo "   1. Create a Pull Request on GitHub / 在 GitHub 上创建 Pull Request"
echo "   2. Wait for review and merge / 等待审查和合并"
echo "   3. Run /deploy after merge / 合并后运行 /deploy"
echo ""
echo "🚀 Happy shipping! / 发布愉快！"
