#!/bin/bash
# Code Review Skill Script / 代码审查技能脚本
# Copyright (c) 2026 OASYS CORE INTERNATIONAL LIMITED / 潤芯國際(香港)有限公司

set -e

echo "🔍 DragonStack Code Review Skill / 代码审查技能"
echo "================================================="
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check if we're in a project directory
if [ ! -f "./DRAGONSTACK.md" ] && [ ! -d "./.dragonstack" ]; then
    echo -e "${YELLOW}⚠️ No DragonStack project detected / 未检测到龙栈项目${NC}"
    echo "Run this from your project root / 请从项目根目录运行"
    exit 1
fi

# Create docs directory if not exists
mkdir -p docs

# Get current date
DATE=$(date +%Y-%m-%d)
OUTPUT_FILE="docs/code-review-${DATE}.md"

echo -e "${BLUE}🔍 Starting code review... / 开始代码审查...${NC}"
echo ""

# Find source files
SOURCE_FILES=$(find . -type f \( -name "*.js" -o -name "*.ts" -o -name "*.py" -o -name "*.java" -o -name "*.go" \) -not -path "./node_modules/*" -not -path "./.git/*" -not -path "./.dragonstack/*" 2>/dev/null | head -20)

if [ -z "$SOURCE_FILES" ]; then
    echo -e "${YELLOW}⚠️ No source files found / 未找到源代码文件${NC}"
    echo "Please add some code files first / 请先添加一些代码文件"
    exit 1
fi

echo "Found source files / 找到源代码文件:"
echo "$SOURCE_FILES" | head -10
echo ""

# Generate review report
cat > "$OUTPUT_FILE" << EOF
# Code Review Report / 代码审查报告

**Date / 日期**: ${DATE}  
**Project / 项目**: $(basename "$(pwd)")  
**Skill / 技能**: /code-review

---

## 1. Review Summary / 审查摘要

| Category / 分类 | Status / 状态 | Count / 数量 |
|----------------|--------------|-------------|
| Critical / 严重 | ⏳ Pending | 0 |
| Warning / 警告 | ⏳ Pending | 0 |
| Info / 信息 | ⏳ Pending | 0 |

---

## 2. Files Reviewed / 审查的文件

\`\`\`
$(echo "$SOURCE_FILES" | head -10)
\`\`\`

---

## 3. Checklist / 检查清单

### Logic Correctness / 逻辑正确性
- [ ] No obvious bugs / 没有明显错误
- [ ] Edge cases handled / 边界情况已处理
- [ ] Error paths covered / 错误路径已覆盖
- [ ] Race conditions checked / 竞争条件已检查

### Code Style / 代码风格
- [ ] Consistent formatting / 格式一致
- [ ] Meaningful variable names / 有意义的变量名
- [ ] Functions are focused / 函数专注
- [ ] Comments where needed / 需要时有注释

### Security / 安全
- [ ] No SQL injection risks / 无 SQL 注入风险
- [ ] No XSS vulnerabilities / 无 XSS 漏洞
- [ ] Input validation / 输入验证
- [ ] Sensitive data protected / 敏感数据受保护

### Performance / 性能
- [ ] No unnecessary loops / 无不必要的循环
- [ ] Efficient data structures / 高效的数据结构
- [ ] No memory leaks / 无内存泄漏
- [ ] Async operations optimized / 异步操作已优化

### Maintainability / 可维护性
- [ ] DRY principle followed / 遵循 DRY 原则
- [ ] Single responsibility / 单一职责
- [ ] Testable code / 可测试代码
- [ ] Documentation complete / 文档完整

---

## 4. Findings / 发现

<!-- Add your findings here / 在这里添加你的发现 -->

### [Severity] Finding Title / [严重级别] 发现标题
- **Location / 位置**: \`file.js:45\`
- **Problem / 问题**: Description of the issue
- **Recommendation / 建议**: How to fix it

---

## 5. Action Items / 行动项

- [ ] Fix critical issues / 修复严重问题
- [ ] Address warnings / 处理警告
- [ ] Add tests for edge cases / 为边界情况添加测试
- [ ] Update documentation / 更新文档

---

## 6. Next Steps / 下一步

- [ ] Run /qa-test for functional testing / 运行 /qa-test 进行功能测试
- [ ] Run /security for security audit / 运行 /security 进行安全审计
- [ ] Run /ship to create PR / 运行 /ship 创建 PR

---

*Generated by DragonStack /code-review skill / 由龙栈 /code-review 技能生成*
EOF

echo -e "${GREEN}✅ Code review report created! / 代码审查报告已创建！${NC}"
echo ""
echo "📄 Output file / 输出文件: ${OUTPUT_FILE}"
echo ""
echo -e "${YELLOW}📋 Next steps / 下一步:${NC}"
echo "   1. Review the checklist in the report / 审查报告中的检查清单"
echo "   2. Fill in the findings section / 填写发现部分"
echo "   3. Fix identified issues / 修复识别的问题"
echo "   4. Run /qa-test for testing / 运行 /qa-test 进行测试"
echo ""
echo "🔍 Happy reviewing! / 审查愉快！"
