#!/bin/bash
# Code Skill Script / 代码生成技能脚本
# Copyright (c) 2026 OASYS CORE INTERNATIONAL LIMITED / 潤芯國際(香港)有限公司

set -e

echo "💻 DragonStack Code Skill / 代码生成技能"
echo "=========================================="
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Check if we're in a project directory
if [ ! -f "./DRAGONSTACK.md" ] && [ ! -d "./.dragonstack" ]; then
    echo -e "${YELLOW}⚠️  No DragonStack project detected / 未检测到龙栈项目${NC}"
    echo "Run this from your project root / 请从项目根目录运行"
    exit 1
fi

# Parse arguments
USE_ACP=""
ACP_AGENT="codex"
LANGUAGE=""
COMPONENT=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --use-acp)
            USE_ACP="true"
            if [[ "$2" != --* ]] && [[ -n "$2" ]]; then
                ACP_AGENT="$2"
                shift
            fi
            shift
            ;;
        --language)
            LANGUAGE="$2"
            shift 2
            ;;
        --component)
            COMPONENT="$2"
            shift 2
            ;;
        --help)
            echo "Usage: ./dragonstack code [options]"
            echo ""
            echo "Options:"
            echo "  --use-acp [agent]   Use ACP agent (codex, claude, pi, kimi)"
            echo "  --language <lang>   Target language (go, python, js, ts, rust)"
            echo "  --component <name>  Component name to generate"
            echo "  --help             Show this help"
            echo ""
            echo "Examples:"
            echo "  ./dragonstack code"
            echo "  ./dragonstack code --use-acp codex"
            echo "  ./dragonstack code --use-acp claude --language go --component api"
            exit 0
            ;;
        *)
            shift
            ;;
    esac
done

# Create directories
mkdir -p src
mkdir -p docs

# Get current date
DATE=$(date +%Y-%m-%d)
OUTPUT_FILE="docs/code-${DATE}.md"

echo -e "${BLUE}💻 Code Generation Framework / 代码生成框架${NC}"
echo ""

# Check if using ACP
if [ "$USE_ACP" = "true" ]; then
    echo -e "${GREEN}🤖 ACP Mode Enabled / ACP 模式已启用${NC}"
    echo "   Agent: $ACP_AGENT"
    echo "   The code will be generated by $ACP_AGENT"
    echo "   代码将由 $ACP_AGENT 生成"
    echo ""
    
    # Check if ACP is available
    if command -v openclaw &> /dev/null; then
        echo -e "${GREEN}✅ OpenClaw detected / 检测到 OpenClaw${NC}"
    else
        echo -e "${YELLOW}⚠️  OpenClaw not found in PATH / PATH 中未找到 OpenClaw${NC}"
        echo "   Falling back to template generation / 回退到模板生成"
        USE_ACP=""
    fi
    echo ""
fi

# Get requirements
echo -e "${YELLOW}💡 What do you want to build? / 你想构建什么？${NC}"
if [ -n "$COMPONENT" ]; then
    echo "   Component: $COMPONENT"
fi
if [ -n "$LANGUAGE" ]; then
    echo "   Language: $LANGUAGE"
fi
echo ""
echo "   Describe the feature/component: / 描述功能/组件："
echo "   (What should it do? Input/output? Business logic?)"
echo "   （它应该做什么？输入/输出？业务逻辑？）"
echo ""
echo "   Type your requirements and press Ctrl+D when done:"
echo "   输入你的需求，完成后按 Ctrl+D："
echo ""

# Read user input
USER_REQUIREMENTS=$(cat)

# Detect language if not specified
if [ -z "$LANGUAGE" ]; then
    if [ -f "go.mod" ]; then
        LANGUAGE="go"
    elif [ -f "package.json" ]; then
        LANGUAGE="javascript"
    elif [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
        LANGUAGE="python"
    elif [ -f "Cargo.toml" ]; then
        LANGUAGE="rust"
    else
        LANGUAGE="[detect-from-project]"
    fi
fi

# ACP Mode - Use external agent
if [ "$USE_ACP" = "true" ]; then
    echo ""
    echo -e "${CYAN}🚀 Starting ACP session with $ACP_AGENT...${NC}"
    echo "   This may take a moment..."
    echo ""
    
    # Create the prompt for ACP
    ACP_PROMPT="Generate code for the following requirement:

Requirements:
${USER_REQUIREMENTS}

Language: ${LANGUAGE}
Component: ${COMPONENT:-"Not specified"}

Please generate:
1. Complete, production-ready code
2. Include comments and documentation
3. Follow best practices for ${LANGUAGE}
4. Include error handling
5. Add unit test examples

Project context:
- Project: $(basename "$(pwd)")
- Date: ${DATE}"

    # Save prompt to file for reference
    echo "$ACP_PROMPT" > ".dragonstack/acp-prompt-${DATE}.txt"
    
    echo -e "${YELLOW}📋 ACP Prompt saved to / ACP 提示已保存至: .dragonstack/acp-prompt-${DATE}.txt${NC}"
    echo ""
    echo -e "${BLUE}To use ACP, run:${NC}"
    echo "  /acp spawn $ACP_AGENT --mode oneshot"
    echo ""
    echo "Or manually with the prompt file above."
    echo ""
fi

# Generate code document
echo ""
echo -e "${BLUE}📝 Generating code specification... / 生成代码规范...${NC}"

cat > "$OUTPUT_FILE" << EOF
# Code Generation Specification / 代码生成规范

**Date / 日期**: ${DATE}  
**Project / 项目**: $(basename "$(pwd)")  
**Skill / 技能**: /code  
**Language / 语言**: ${LANGUAGE}  
**Component / 组件**: ${COMPONENT:-"Not specified / 未指定"}  
**ACP Agent / ACP 代理**: ${USE_ACP:+$ACP_AGENT}${USE_ACP:-"None / 无"}

---

## 1. Requirements / 需求

${USER_REQUIREMENTS}

---

## 2. Implementation Plan / 实现计划

### 2.1 File Structure / 文件结构

\`\`\`
src/
├── ${COMPONENT:-feature}/
│   ├── ${COMPONENT:-feature}.${LANGUAGE}
│   ├── ${COMPONENT:-feature}_test.${LANGUAGE}
│   └── README.md
└── index.${LANGUAGE}
\`\`\`

### 2.2 Key Functions / 关键函数

| Function / 函数 | Input / 输入 | Output / 输出 | Description / 描述 |
|----------------|-------------|--------------|-------------------|
| [function1] | [params] | [return] | [description] |
| [function2] | [params] | [return] | [description] |

---

## 3. Code Template / 代码模板

### 3.1 Main Implementation / 主实现

EOF

# Add language-specific template
case $LANGUAGE in
    go)
        cat >> "$OUTPUT_FILE" << 'EOF'
```go
package main

import (
    "context"
    "fmt"
    "log"
)

// Config holds the configuration / Config 保存配置
type Config struct {
    // Add configuration fields / 添加配置字段
}

// Service represents the service / Service 表示服务
type Service struct {
    config Config
}

// NewService creates a new service / NewService 创建新服务
func NewService(cfg Config) *Service {
    return &Service{
        config: cfg,
    }
}

// Process handles the main logic / Process 处理主要逻辑
func (s *Service) Process(ctx context.Context, input string) (string, error) {
    // TODO: Implement business logic / 实现业务逻辑
    return "", nil
}

func main() {
    cfg := Config{}
    svc := NewService(cfg)
    
    ctx := context.Background()
    result, err := svc.Process(ctx, "input")
    if err != nil {
        log.Fatal(err)
    }
    
    fmt.Println(result)
}
```
EOF
        ;;
    python)
        cat >> "$OUTPUT_FILE" << 'EOF'
```python
"""
Module description / 模块描述
"""

from typing import Optional, Dict, Any
import logging

logger = logging.getLogger(__name__)


class Service:
    """Service class description / 服务类描述"""
    
    def __init__(self, config: Dict[str, Any]):
        """
        Initialize service / 初始化服务
        
        Args:
            config: Configuration dictionary / 配置字典
        """
        self.config = config
    
    def process(self, input_data: str) -> str:
        """
        Process the input / 处理输入
        
        Args:
            input_data: Input string / 输入字符串
            
        Returns:
            Processed result / 处理结果
            
        Raises:
            ValueError: If input is invalid / 如果输入无效
        """
        # TODO: Implement business logic / 实现业务逻辑
        pass


def main():
    """Main entry point / 主入口点"""
    config = {}
    service = Service(config)
    
    result = service.process("input")
    print(result)


if __name__ == "__main__":
    main()
```
EOF
        ;;
    javascript|js|typescript|ts)
        cat >> "$OUTPUT_FILE" << 'EOF'
```typescript
/**
 * Service class description / 服务类描述
 */
export interface Config {
  // Add configuration fields / 添加配置字段
}

export interface Input {
  // Add input fields / 添加输入字段
}

export interface Output {
  // Add output fields / 添加输出字段
}

export class Service {
  private config: Config;

  constructor(config: Config) {
    this.config = config;
  }

  /**
   * Process the input / 处理输入
   * @param input - Input data / 输入数据
   * @returns Processed result / 处理结果
   */
  async process(input: Input): Promise<Output> {
    // TODO: Implement business logic / 实现业务逻辑
    throw new Error("Not implemented / 未实现");
  }
}

// Usage example / 使用示例
async function main() {
  const config: Config = {};
  const service = new Service(config);
  
  const result = await service.process({});
  console.log(result);
}

main().catch(console.error);
```
EOF
        ;;
    *)
        cat >> "$OUTPUT_FILE" << 'EOF'
```
// TODO: Implement in your target language / 用目标语言实现
// Language: [Your Language]

// Key components to implement / 需要实现的关键组件:
// 1. Configuration structure / 配置结构
// 2. Main service class/function / 主服务类/函数
// 3. Error handling / 错误处理
// 4. Input validation / 输入验证
```
EOF
        ;;
esac

cat >> "$OUTPUT_FILE" << EOF

### 3.2 Test Template / 测试模板

EOF

case $LANGUAGE in
    go)
        cat >> "$OUTPUT_FILE" << 'EOF'
```go
package main

import (
    "context"
    "testing"
)

func TestService_Process(t *testing.T) {
    tests := []struct {
        name    string
        input   string
        want    string
        wantErr bool
    }{
        {
            name:    "valid input",
            input:   "test",
            want:    "expected",
            wantErr: false,
        },
    }
    
    for _, tt := range tests {
        t.Run(tt.name, func(t *testing.T) {
            svc := NewService(Config{})
            got, err := svc.Process(context.Background(), tt.input)
            
            if (err != nil) != tt.wantErr {
                t.Errorf("Process() error = %v, wantErr %v", err, tt.wantErr)
                return
            }
            
            if got != tt.want {
                t.Errorf("Process() = %v, want %v", got, tt.want)
            }
        })
    }
}
```
EOF
        ;;
    python)
        cat >> "$OUTPUT_FILE" << 'EOF'
```python
import pytest
from your_module import Service


class TestService:
    """Test suite for Service / Service 的测试套件"""
    
    @pytest.fixture
    def service(self):
        """Create service fixture / 创建服务 fixture"""
        return Service({})
    
    def test_process_valid_input(self, service):
        """Test process with valid input / 测试有效输入的处理"""
        result = service.process("valid input")
        assert result is not None
    
    def test_process_invalid_input(self, service):
        """Test process with invalid input / 测试无效输入的处理"""
        with pytest.raises(ValueError):
            service.process("")
```
EOF
        ;;
    *)
        cat >> "$OUTPUT_FILE" << 'EOF'
```
// Add tests for your language / 为你的语言添加测试
// Test cases to cover / 需要覆盖的测试用例:
// 1. Valid input / 有效输入
// 2. Invalid input / 无效输入
// 3. Edge cases / 边界情况
// 4. Error handling / 错误处理
```
EOF
        ;;
esac

cat >> "$OUTPUT_FILE" << EOF

---

## 4. Best Practices Checklist / 最佳实践检查清单

- [ ] Code follows language conventions / 代码遵循语言约定
- [ ] Functions are small and focused / 函数小而专注
- [ ] Meaningful variable names / 有意义的变量名
- [ ] Error handling implemented / 实现了错误处理
- [ ] Input validation / 输入验证
- [ ] Logging added / 添加了日志
- [ ] Unit tests included / 包含单元测试
- [ ] Documentation complete / 文档完整

---

## 5. Next Steps / 下一步

EOF

if [ "$USE_ACP" = "true" ]; then
    cat >> "$OUTPUT_FILE" << EOF
- [ ] Run ACP session with $ACP_AGENT / 使用 $ACP_AGENT 运行 ACP 会话
  \`\`\`
  /acp spawn $ACP_AGENT --mode oneshot
  "Generate production-ready code based on: .dragonstack/acp-prompt-${DATE}.txt"
  \`\`
- [ ] Review generated code / 审查生成的代码
- [ ] Run /code-review for quality check / 运行 /code-review 进行质量检查
- [ ] Run /test for test coverage / 运行 /test 进行测试覆盖

EOF
else
    cat >> "$OUTPUT_FILE" << EOF
- [ ] Implement the code based on template / 基于模板实现代码
- [ ] Add error handling / 添加错误处理
- [ ] Write unit tests / 编写单元测试
- [ ] Run /code-review for quality check / 运行 /code-review 进行质量检查
- [ ] Run /test for test coverage / 运行 /test 进行测试覆盖

EOF
fi

cat >> "$OUTPUT_FILE" << EOF
---

*Generated by DragonStack /code skill / 由龙栈 /code 技能生成*
EOF

echo ""
echo -e "${GREEN}✅ Code specification created! / 代码规范已创建！${NC}"
echo ""
echo "📄 Output file / 输出文件: ${OUTPUT_FILE}"

if [ "$USE_ACP" = "true" ]; then
    echo "📝 ACP Prompt / ACP 提示: .dragonstack/acp-prompt-${DATE}.txt"
fi

echo ""
echo -e "${YELLOW}📋 Next steps / 下一步:${NC}"

if [ "$USE_ACP" = "true" ]; then
    echo "   1. Run ACP to generate code: / 运行 ACP 生成代码:"
    echo "      /acp spawn $ACP_AGENT --mode oneshot"
    echo "      'Generate code based on .dragonstack/acp-prompt-${DATE}.txt'"
    echo "   2. Review and refine the generated code / 审查和完善生成的代码"
else
    echo "   1. Implement code based on the template / 基于模板实现代码"
    echo "   2. Add error handling and validation / 添加错误处理和验证"
fi

echo "   3. Run /code-review for quality check / 运行 /code-review 进行质量检查"
echo "   4. Run /test for test coverage / 运行 /test 进行测试覆盖"
echo ""
echo "💻 Happy coding! / 编码愉快！"
